### PR TITLE
Use Sphinx for documentation instead of mkdocs

### PR DESCRIPTION
**Pull request by kretep**
Migrate documentation from mkdocs to sphinx. Creating a separate PR for this, to make the one with mixed improvements (#79) more manageable.

Biggest advantage of moving to sphinx is that the API reference can be automatically generated (this didn't work with mkdocs).

### CODE REVIEW

**Comment by kretep** [comment]
The "build" action is failing as expected; it is replaced by "build-and-test" in #79 .

**Comment by vedran-kasalica** [comment]
> The "build" action is failing as expected; it is replaced by "build-and-test" in #79 .

To fix the issue, should we then update or remove `.github/workflows/python-package.yml`?

**Review by vedran-kasalica — APPROVED** [review]
I agree with the idea of switching to Sphinx, and the changes in the PR reflect that well.

**Comment by kretep** [comment]
> To fix the issue, should we then update or remove `.github/workflows/python-package.yml`?

We can remove it

**Comment by vedran-kasalica** [comment]
> > To fix the issue, should we then update or remove `.github/workflows/python-package.yml`?
> 
> We can remove it

Do you prefer doing it before or after we merge this PR?

**Comment by kretep** [comment]
Its removal is also part of #79, so I was thinking to just not do it twice, although there won't be any conflicts if we remove it here

**Pull request merged**
