### PR TITLE
Update from dedicated repo

### PR DESCRIPTION
**Pull request by kretep**
Update JOSS paper

### CODE REVIEW

**Review by vedran-kasalica — APPROVED** [review]
The changes look good. I was thinking that we could use the [figure referencing format](https://joss.readthedocs.io/en/latest/submitting.html#tables-and-figures) provided by JOSS, but when I tried to implement it in our `paper-tsdf` repo (see the [commit](https://github.com/biomarkersParkinson/paper-tsdf/commit/1b90b73822bbaa30cc28d0809ee709d27f50ccea)) the output PDF was not well structured (contains `??` instead of `Figure 1`). Maybe it's better to leave the reference as it is. I saw that some JOSS publications do the same.

**Comment by vedran-kasalica** [comment]
I suggest creating a folder `paper` and adding the 3 files to it. That's a common practice which keeps the repo clean.

**Comment by kretep** [comment]
> The changes look good. I was thinking that we could use the [figure referencing format](https://joss.readthedocs.io/en/latest/submitting.html#tables-and-figures) provided by JOSS, but when I tried to implement it in our `paper-tsdf` repo (see the [commit](https://github.com/biomarkersParkinson/paper-tsdf/commit/1b90b73822bbaa30cc28d0809ee709d27f50ccea)) the output PDF was not well structured (contains `??` instead of `Figure 1`). Maybe it's better to leave the reference as it is. I saw that some JOSS publications do the same.

I tried that, but also didn't manage to get it to work

**Comment by kretep** [comment]
> I suggest creating a folder `paper` and adding the 3 files to it. That's a common practice which keeps the repo clean.

That would have my preference also, but I read somewhere that they require putting it in the root to make it findable. The alternative is to keep it in a dedicated branch an not merge it to main.

**Comment by vedran-kasalica** [comment]
> > I suggest creating a folder `paper` and adding the 3 files to it. That's a common practice which keeps the repo clean.
> 
> That would have my preference also, but I read somewhere that they require putting it in the root to make it findable. The alternative is to keep it in a dedicated branch an not merge it to main.

I looked at ~10 examples of JOSS publications today, looking into the Fig references, and almost all of them had a separate folder for the paper. I remember that I did the same when I submitted APE to JOSS. So I am not sure whether keeping it in the root is required.

**Pull request merged**
