### PR TITLE
Refactor code

### LINKED ISSUE #35: Refactor some code
* Complete removing load_binary from metadata class (make use of functions uniform accross package, i.e. no methods on classes)
* Expose functions at top-level of package
* Maybe more?

### PR DESCRIPTION
**Pull request by vedran-kasalica**
Progress:
- [x] Complete removing load_binary from metadata class (make use of functions uniform accross package, i.e. no methods on classes)
- [x] Expose functions at top-level of package
- [x] Somehting else?

Closes #35

### CODE REVIEW

**Comment by vedran-kasalica** [comment]
I finished the following tasks:
- removed **load_binary** from tsdf class
- fixed read_binary.**load_binary_from_metadata**

@kretep, you can continue doing the remaining tasks as agreed

**Comment by kretep** [comment]
This now also addresses #24

**Comment by kretep** [comment]
The functions are now exposed at the top-level of the package, although the modules are still in there too (not sure how to hide them...)

**Comment by kretep** [comment]
To be complete: while restructuring the package, I also refactored the tests. The reference to the test data directory was not working properly; now using a plugin for that.

Also simplified and split up the usage documentation (notebooks)

**Review by vedran-kasalica — COMMENTED** [review]
The code looks good, the tests and the notebooks were nicely refactored .

**Comment by vedran-kasalica** [comment]
Closes #24

**Review by kretep — APPROVED** [review]

**Pull request merged**
